### ISSUE TITLE
データセットによってトリミングの指定方法が違う

### ISSUE THREAD

**Issue by Shakshi3104** [haselab-dev/sensorutils#23]
前後2秒のトリミングをする場合、
- HASCのローダは、 `hasc.load(…, ftrim=2*100, btrim:2*100)`
- WISDMのローダは、`wisdm.load(…, ftrim_sec=2, btrim_sec=2)`

と指定方法が異なる。そのため、誤る可能性がある。なので、秒数かサンプル数かのどちらかに統一されると望ましい。

**Comment by Shakshi3104** [comment]
よく考えたら、HASCは50Hzと100Hzのデータが混ざっているので、秒数を指定するのめんどくさいことに気づいた。

**Comment by foo2810** [comment]
HASCのトリミング指定の方法が現状のままでいい気がするけど、ドキュメントにこの旨を入れた方いいかもしれない。

**Comment by foo2810** [comment]
52f4f7c でドキュメントの加筆を行ったのでfix
